### ISSUE TITLE
CRSPR have significant difference with RNAi

### ISSUE THREAD

**Issue by Shicheng-Guo** [kenichi-shimada/shinyDepMap#4]
Hi Kenichi, 

Great tool!! Is there any script to pick-up all the genes whose CRSPR have significant difference with RNAi like below? 

![image](https://user-images.githubusercontent.com/6641283/144437134-0af26966-c09c-4e25-bdea-83873957365c.png)

Thanks

Shicheng

**Comment by kenichi-shimada** [comment]
Hi Sicheng, thanks for your note! I haven't particularly implemented it yet,but you could easily achieve that by the code processing DepMap data. Please refer to [this repo](https://github.com/kenichi-shimada/depmap-analysis). Thanks!
